### PR TITLE
Features/vt 20 import workflow api

### PR DESCRIPTION
**Pull request by vinhvoniteco**
hi,
this request is developed on  Import Organization Workflow API at [VT-20](http://jira.niteco.se:8080/browse/VT-20).

### CODE REVIEW

**Comment by eMazeika** [comment]
VirtoCommerce.OrderModule.Core.Models: don't end the class names with "Model"

JsonImportModel: class not used? In case you need it only as a parameter for API, move it to Web project

OrganizationWorkflow class should derive from AuditableEntity

SearchCriteriaModel: rename to WorkflowSearchCriteria. And derive from SearchCriteriaBase

IImportWorkflowService: rename to IWorkflowService

List<OrganizationWorkflowModel> Search(SearchCriteriaModel searchWorkflowCriteria);
refactor to
GenericSearchResult<OrganizationWorkflow> Search(WorkflowSearchCriteria criteria)

OrganizationWorkflowModel ImportWorkflow(OrganizationWorkflowModel workflowModel);
and
OrganizationWorkflowModel ImportOrUpdateWorkflow(OrganizationWorkflowModel workflowModel);
are duplicates. Remove duplecate and rename to "SaveWorkflow"

OrganizationWorkflowEntity should contain 3 methods:
public virtual OrganizationWorkflow ToModel(OrganizationWorkflow organizationWorkflow)
public virtual OrganizationWorkflowEntity FromModel(OrganizationWorkflow organizationWorkflow)
public virtual void Patch(OrganizationWorkflowEntity target)

Change
new OrganizationWorkflowEntity
to
AbstractTypeFactory<CustomerReviewEntity>.TryCreateInstance()

Convert between OrganizationWorkflowEntity and OrganizationWorkflow only inside OrganizationWorkflowEntity class. Not outside.

private bool IsValidJson(string jsonPath) should return bool value, not exceptions 

class OrganizationWorkflowModelApi not needed. Use OrganizationWorkflow from Core project

Don't change localization files if you don't actually translate the values (de, ru languages)

Scripts:
Don't access blade.parentBlade; pass it's value to new blade definition while initializing (new blade)

bladeNavigationService.setError calls blade.isLoading = false internally. No need to reset:
blade.isLoading = false;
before calling bladeNavigationService.setError....

virtoCommerce.orderModule.workflowWidgetController
Change: 
blade = $scope.blade;
to 
var blade = $scope.blade;

**Review by eMazeika — CHANGES_REQUESTED** [review]
VirtoCommerce.OrderModule.Core.Models: don't end the class names with "Model"

JsonImportModel: class not used? In case you need it only as a parameter for API, move it to Web project

OrganizationWorkflow class should derive from AuditableEntity

SearchCriteriaModel: rename to WorkflowSearchCriteria. And derive from SearchCriteriaBase

IImportWorkflowService: rename to IWorkflowService

List<OrganizationWorkflowModel> Search(SearchCriteriaModel searchWorkflowCriteria);
refactor to
GenericSearchResult<OrganizationWorkflow> Search(WorkflowSearchCriteria criteria)

OrganizationWorkflowModel ImportWorkflow(OrganizationWorkflowModel workflowModel);
and
OrganizationWorkflowModel ImportOrUpdateWorkflow(OrganizationWorkflowModel workflowModel);
are duplicates. Remove duplecate and rename to "SaveWorkflow"

OrganizationWorkflowEntity should contain 3 methods:
public virtual OrganizationWorkflow ToModel(OrganizationWorkflow organizationWorkflow)
public virtual OrganizationWorkflowEntity FromModel(OrganizationWorkflow organizationWorkflow)
public virtual void Patch(OrganizationWorkflowEntity target)

Change
new OrganizationWorkflowEntity
to
AbstractTypeFactory<CustomerReviewEntity>.TryCreateInstance()

Convert between OrganizationWorkflowEntity and OrganizationWorkflow only inside OrganizationWorkflowEntity class. Not outside.

private bool IsValidJson(string jsonPath) should return bool value, not exceptions 

class OrganizationWorkflowModelApi not needed. Use OrganizationWorkflow from Core project

Don't change localization files if you don't actually translate the values (de, ru languages)

Scripts:
Don't access blade.parentBlade; pass it's value to new blade definition while initializing (new blade)

bladeNavigationService.setError calls blade.isLoading = false internally. No need to reset:
blade.isLoading = false;
before calling bladeNavigationService.setError....

virtoCommerce.orderModule.workflowWidgetController
Change: 
blade = $scope.blade;
to 
var blade = $scope.blade;

**Comment by vinhvoniteco** [comment]
> class OrganizationWorkflowModelApi not needed. Use OrganizationWorkflow from Core project

hi Egis,
Because in OrganizationWorkflow class, we have some unuseful fields which user will call api service (ex: CreatedDate, ModifiedDate, Id....). They will make user confuse because they will be autogenerated by system and don't need to add them in model api.
Please let me know your advice.

cc: @tonhuynh 
Thanks

**Comment by vinhvoniteco** [comment]
hi @eMazeika 
Please help me to merge this  pull request. I resolved all conflicts.
thank you
best regards,
Vinh Vo

**Comment by eMazeika** [comment]
> > class OrganizationWorkflowModelApi not needed. Use OrganizationWorkflow from Core project
> 
> hi Egis,
> Because in OrganizationWorkflow class, we have some unuseful fields which user will call api service (ex: CreatedDate, ModifiedDate, Id....). They will make user confuse because they will be autogenerated by system and don't need to add them in model api.
> Please let me know your advice.
> 
> cc: @tonhuynh
> Thanks

Who will be confused? Tell them that there are system fields that they should ignore.

**Review by eMazeika — CHANGES_REQUESTED** [review]
OrganizationWorkflow class should derive from AuditableEntity

OrganizationWorkflowEntity:
refactor
public virtual OrganizationWorkflow ToModel()
to
public virtual OrganizationWorkflow ToModel(OrganizationWorkflow organizationWorkflow)

Implementation of Patch(OrganizationWorkflowEntity target) is incorrect. Check other Entity classes for samples.

Don't return InternalServerError from API. Return request error (4xx) instead.

remove unused class OrganizationWorkflowModelApi

Don't change localization files if you don't actually translate the values (de, ru languages)

Scripts:
rename 
virtoCommerce.orderModule.uploadFlowController
to 
virtoCommerce.orderModule.uploadWorkflowController

rename workflowUploadWidget.js
to workflow-widget.js (as controller inside it is named workflowWidgetController)

**Pull request closed without merging**
